### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by denise0593** [aineniamh/squirrel#2]
Hi! 
I'm trying the software using the command line:
```
squirrel multi_con_2518.fasta
```
but I'm getting the following error:

```
Traceback (most recent call last):
  File "/home/delavezz/anaconda3/envs/squirrel/lib/python3.8/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/home/delavezz/anaconda3/envs/squirrel/lib/python3.8/site-packages/snakemake/workflow.py", line 1043, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/home/delavezz/anaconda3/envs/squirrel/lib/python3.8/site-packages/snakemake/dag.py", line 2176, in stats
    yield tabulate(rows, headers="keys")
  File "/home/delavezz/anaconda3/envs/squirrel/lib/python3.8/site-packages/tabulate/__init__.py", line 2048, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/home/delavezz/anaconda3/envs/squirrel/lib/python3.8/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/delavezz/anaconda3/envs/squirrel/lib/python3.8/site-packages/tabulate/__init__.py", line 1471, in <lambda>
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/delavezz/anaconda3/envs/squirrel/lib/python3.8/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/home/delavezz/anaconda3/envs/squirrel/lib/python3.8/site-packages/snakemake/rules.py", line 1127, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'
```

**Comment by aineniamh** [comment]
Hi @denise0593. this is an update to tabulate that has impacted a few different tools that also use snakemake. I've pushed a pinned version of tabulate and added some tests into this repo to see if that resolves your issue!

**Comment by denise0593** [comment]
Hi @aineniamh now it works! Thanks a lot!

**Comment by aineniamh** [comment]
Excellent, glad it's sorted!
