### ISSUE TITLE
Forgetting to specify an input file on the command line produces an uninformative error

### ISSUE THREAD

**Issue by rambaut** [aineniamh/squirrel#53]
Command line:
`squirrel --clade cladei`

produces:

```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/squirrel/bin/squirrel", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/squirrel/lib/python3.10/site-packages/squirrel/command.py", line 78, in main
    config[KEY_OUTFILE],config[KEY_CDS_OUTFILE],config[KEY_OUTFILENAME],config[KEY_OUTFILE_STEM],config[KEY_OUTDIR] = io.set_up_outfile(args.outfile,cwd,args.input, config[KEY_OUTFILE],config[KEY_OUTDIR])
  File "/opt/miniconda3/envs/squirrel/lib/python3.10/site-packages/squirrel/utils/io_parsing.py", line 68, in set_up_outfile
    if not os.path.exists(os.path.join(cwd, query_arg[0])):
IndexError: list index out of range
```

**Comment by aineniamh** [comment]
handle the index error explicitly now- io output file fxn run prior to the io fasta finder- now the handle in both places
