### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by lingxuan85511** [aineniamh/squirrel#64]
Hi Aine,

I got this error message during during executing. Any advice on how to get this fixed?

Squirrel v 1.0.10 was used and the command was as follow:

squirrel --clade cladei --run-apobec3-phylo --outgroups KJ642615,KJ642616,KJ642617 -t 10 -o ./squirrel_output/ data_with_outgroup.fasta

Error report:

Error in rule reconstruction_analysis:
    jobid: 0
    input: /public1/home/sch2716/Monkeypox/squirrel_results/./squirrel_output/data_with_outgroup.tree, /public1/home/sch2716/Monkeypox/squirrel_results/./squirrel_output/data_with_outgroup.tree.state, /public1/home/sch2716/Monkeypox/squirrel_results/./squirrel_output/data_with_outgroup.aln.fasta
    output: /public1/home/sch2716/Monkeypox/squirrel_results/./squirrel_output/data_with_outgroup.tree.svg

RuleException:
TypeError in file /public1/home/sch2716/Programs/MINICONDA3/miniconda3/envs/squirrel/lib/python3.10/site-packages/squirrel/scripts/reconstruction.smk, line 77:
ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
  File "/public1/home/sch2716/Programs/MINICONDA3/miniconda3/envs/squirrel/lib/python3.10/site-packages/squirrel/scripts/reconstruction.smk", line 77, in __rule_reconstruction_analysis
  File "/public1/home/sch2716/Programs/MINICONDA3/miniconda3/envs/squirrel/lib/python3.10/site-packages/squirrel/utils/reconstruction_functions.py", line 725, in run_full_analysis
  File "/public1/home/sch2716/Programs/MINICONDA3/miniconda3/envs/squirrel/lib/python3.10/site-packages/squirrel/utils/reconstruction_functions.py", line 357, in load_info
  File "/public1/home/sch2716/Programs/MINICONDA3/miniconda3/envs/squirrel/lib/python3.10/site-packages/squirrel/utils/reconstruction_functions.py", line 255, in make_reconstruction_tree_figure_w_labels
  File "/public1/home/sch2716/Programs/MINICONDA3/miniconda3/envs/squirrel/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1759, in subplots
  File "/public1/home/sch2716/Programs/MINICONDA3/miniconda3/envs/squirrel/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1027, in figure
  File "/public1/home/sch2716/Programs/MINICONDA3/miniconda3/envs/squirrel/lib/python3.10/site-packages/matplotlib/pyplot.py", line 550, in new_figure_manager
  File "/public1/home/sch2716/Programs/MINICONDA3/miniconda3/envs/squirrel/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 3506, in new_figure_manager
  File "/public1/home/sch2716/Programs/MINICONDA3/miniconda3/envs/squirrel/lib/python3.10/site-packages/matplotlib/figure.py", line 2565, in __init__
  File "/public1/home/sch2716/Programs/MINICONDA3/miniconda3/envs/squirrel/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-12-11T155059.261422.snakemake.log
[32mQuery file:	[0m/public1/home/sch2716/Monkeypox/squirrel_results/data_with_outgroup.fasta
[32mAlignment complete.[0m
Traceback (most recent call last):
  File "/public1/home/sch2716/Programs/MINICONDA3/miniconda3/envs/squirrel/bin/squirrel", line 8, in <module>
    sys.exit(main())
  File "/public1/home/sch2716/Programs/MINICONDA3/miniconda3/envs/squirrel/lib/python3.10/site-packages/squirrel/command.py", line 169, in main
    make_output_report(report,mask_file,config)
  File "/public1/home/sch2716/Programs/MINICONDA3/miniconda3/envs/squirrel/lib/python3.10/site-packages/squirrel/utils/make_report.py", line 37, in make_output_report
    data_for_report["phylo_svg_string"] = get_tree_svg(tree_image_file)
  File "/public1/home/sch2716/Programs/MINICONDA3/miniconda3/envs/squirrel/lib/python3.10/site-packages/squirrel/utils/make_report.py", line 23, in get_tree_svg
    with open(tree_image_file,"r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/public1/home/sch2716/Monkeypox/squirrel_results/./squirrel_output/data_with_outgroup.tree.svg'

**Comment by aineniamh** [comment]
Hi, happy to look into this- what the error suggests is that there is something weird going on with the width and height calculation. I'm going to have a go at fixing, but it seems to be an issue arising in the case of your data (possibly to do with the number of sequences or size of the tree). If it was possible to share the anonymised sequences, it might help with debugging!

**Comment by lingxuan85511** [comment]
Hi Aine,

The squirrel v 1.0.10 performed correctly with the same input data. I think this information will help you quickly identify where the issue lies.

**Comment by pvanheus** [comment]
Hi! A colleague reported the same error and I can reproduce it with squirrel 1.0.12 using the data from https://www.nature.com/articles/s41591-025-03582-1 - PQ305763-PQ305728 - as a test set. As @lingxuan85511 reports, this error does not occur with squirrel v 1.0.10, nor does it occur with squirrel v 1.0.11.

**Comment by pvanheus** [comment]
I am now confused because @lingxuan85511 mentioned this as happening with 1.0.10 - but it doesn't for me. And you commit a fix for exactly this @aineniamh - I'm doing to investigate further.

**Comment by pvanheus** [comment]
So as I understand it the bug started with the use of subplot in 1.0.12 (https://github.com/aineniamh/squirrel/blob/1.0.12/squirrel/utils/reconstruction_functions.py#L255) and height / width being None. I see @aineniamh has committed a fix in #65 and a workaround until a new release is to explicitly set `--fig-width` and `--fig-height`, so e.g.

```bash
squirrel --include-background --run-apobec3-phylo --clade cladeib --fig-height 40 --fig-width 25 sequences/all.fasta
```

**Comment by lingxuan85511** [comment]
Thank you for providing solution to this error. I repeated the analysis with specifying these two parameters under squirrel v 1.0.12, the program then ended correctly.

**Comment by aineniamh** [comment]
Have tagged a new release to include this case handling! 
https://github.com/aineniamh/squirrel/releases/tag/1.0.13
